# Generated by Django 4.2.2 on 2024-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='198635', max_length=6, verbose_name='Код верификации'),
        ),
    ]
