# Generated by Django 4.2.2 on 2024-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='439105', max_length=6, verbose_name='Код верификации'),
        ),
    ]
