# Generated by Django 4.2.2 on 2024-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID пользователя Telegram для отправки уведомлений', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='490362', max_length=6, verbose_name='Код верификации'),
        ),
    ]
