# Generated by Django 4.2.2 on 2024-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_telegram_chat_id_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='534071', max_length=6, verbose_name='Код верификации'),
        ),
    ]
