# Generated by Django 4.2.2 on 2024-09-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='default_username', max_length=50, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='921857', max_length=6, verbose_name='Код верификации'),
        ),
    ]
