# Generated by Django 4.2.2 on 2024-09-27 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Конец периода'),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Начало периода'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('1', 'Каждый 1 день'), ('2', 'Каждые 2 дня'), ('3', 'Каждые 3 дня'), ('4', 'Каждые 4 дня'), ('5', 'Каждые 5 дней'), ('6', 'Каждые 6 дней'), ('7', 'Каждые 7 дней')], default='1', help_text='Повторять...', max_length=50, verbose_name='Периодичность'),
        ),
    ]
