# Generated by Django 4.2.2 on 2024-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_end_date_alter_habit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('active', 'Активна'), ('completed', 'Завершена')], default='created', max_length=50, verbose_name='Статус'),
        ),
    ]
