# Generated by Django 4.2.2 on 2024-09-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_to_complete',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete_temp',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Время на выполнение (в минутах)'),
        ),
    ]
