# Generated by Django 4.2.2 on 2024-09-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_habit_time_to_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='time_to_complete_temp',
            new_name='time_to_complete',
        ),
    ]
