# Generated by Django 4.2.2 on 2024-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_rename_time_to_complete_temp_habit_time_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего уведомления'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('1 min', 'Каждые 1 мин.'), ('1', 'Каждый 1 день'), ('2', 'Каждые 2 дня'), ('3', 'Каждые 3 дня'), ('4', 'Каждые 4 дня'), ('5', 'Каждые 5 дней'), ('6', 'Каждые 6 дней'), ('7', 'Каждые 7 дней')], default='1', help_text='Повторять...', max_length=50, verbose_name='Периодичность'),
        ),
    ]
