# Generated by Django 4.2.2 on 2024-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habit_last_notification_time_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, default='Где угодно', help_text='Укажите место, в котором необходимо выполнять привычку', max_length=50, null=True, verbose_name='Место'),
        ),
    ]
