# Generated by Django 4.2.2 on 2024-09-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_alter_habit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('1 min', 'Каждые 1 мин.'), ('3 min', 'Каждые 3 мин.'), ('1', 'Каждый 1 день'), ('2', 'Каждые 2 дня'), ('3', 'Каждые 3 дня'), ('4', 'Каждые 4 дня'), ('5', 'Каждые 5 дней'), ('6', 'Каждые 6 дней'), ('7', 'Каждые 7 дней')], default='1', help_text='Повторять...', max_length=50, verbose_name='Периодичность'),
        ),
    ]
