# Generated by Django 4.2.2 on 2024-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_notification_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующего уведомления'),
        ),
    ]
